/** Русские подписи секций и полей настроек; нет подписи — заголовок схемы. */
export const SECTION_LABELS: Record<string, string> = {
	engine: 'Движок',
	features: 'Функции',
	strategy: 'Стратегия и дела',
	daily: 'Задания дня',
	lottery: 'Лотерея',
	battle: 'Битва',
	stocks: 'Акции',
	sleep: 'Сон',
	metro: 'Метро',
	food: 'Еда',
	levelup: 'Прокачка',
	tangerine: 'Мандарин',
	chats: 'Чаты',
	telegram: 'Telegram',
	retention: 'Хранение'
};

/** Порядок секций в меню (как в согласованном макете); остальные — после, в порядке схемы. */
export const SECTION_ORDER = [
	'engine',
	'features',
	'strategy',
	'daily',
	'lottery',
	'battle',
	'stocks',
	'sleep',
	'metro',
	'food',
	'levelup',
	'tangerine',
	'chats',
	'telegram',
	'retention'
];

export const FIELD_LABELS: Record<string, string> = {
	'engine.mode': 'Режим',
	'engine.killed': 'Kill включён',
	'engine.kill_reason': 'Причина kill',
	'engine.paused': 'Пауза планировщика',
	'engine.min_request_interval_s': 'Пауза между запросами, с',
	'engine.antiflood_retry_max': 'Повторов после антифлуда',
	'engine.antiflood_pause_s': 'Пауза антифлуда, с',
	'engine.action_ttl_s': 'Срок жизни действия в очереди, с',
	'engine.default_expect_timeout_s': 'Ожидание ответа игры, с',
	'engine.click_answer_timeout_s': 'Ожидание ответа на клик, с',
	'engine.recovered_react_max_age_min': 'Реагировать на догнанные сообщения не старше, мин',
	'engine.refresh_min_interval_s': 'Обновлять экраны не чаще, с',
	'engine.state_stale_after_min': 'Состояние устаревает через, мин',
	'engine.urgent_while_paused': 'Срочное на паузе',
	'engine.manual_while_paused': 'Ручное на паузе',
	'telegram.expected_user_id': 'Ожидаемый аккаунт Telegram (user_id)',
	'chats.game_chat_id': 'Чат игры',
	'chats.swinfo_chat_id': 'Чат SWINFO',
	'chats.swinfo_user_id': 'Бот SWINFO',
	'chats.smoothie_channel_id': 'Канал рецептов смузи',
	'chats.tangerine_chat_id': 'Чат мандаринов',
	'chats.tangerine_reply_to': 'Сообщение для /gt',
	'chats.bulls_invite_chat_id': 'Чат приглашений к биржевикам',
	'features.deeds': 'Дела',
	'features.books': 'Книги',
	'features.fastfood': 'Фастфуд',
	'features.cards_containers': 'Карты и контейнеры',
	'features.gorbushka': 'Горбушка',
	'features.sleep': 'Сон',
	'features.levelup': 'Прокачка навыков',
	'features.metro': 'Метро',
	'features.battle': 'Битва',
	'features.factory': 'Фабрика',
	'features.bulls': 'Биржевики',
	'features.stocks_dump': 'Слив налички в акции',
	'features.smoothie': 'Смузи',
	'features.tangerine': 'Мандарин',
	'features.lottery': 'Лотерея',
	'features.casino': 'Казино',
	'features.arena': 'Арена',
	'features.pet_feast': 'Пир пета',
	'features.daily_tasks': 'Ежедневные задания',
	'features.robbery_defense': 'Защита от ограбления',
	'features.paid_info': 'Платная информация',
	'features.seasonal': 'Сезонные ивенты',
	'strategy.weight_xp': 'Вес опыта',
	'strategy.weight_money': 'Вес денег',
	'strategy.weight_resources': 'Вес ресурсов',
	'strategy.exp_scale': 'Типичный 💡 на 1🔥',
	'strategy.money_scale': 'Типичные 💵 на 1🔥',
	'strategy.resource_scale': 'Типичные ресурсы на 1🔥',
	'strategy.focus': 'Основные дела',
	'strategy.deeds': 'Разрешённые дела',
	'food.order': 'Порядок фастфуда',
	'food.banana_reserve': 'Запас бананов',
	'sleep.duration_h': 'Длительность сна, ч',
	'sleep.lead_min': 'Ложиться до дедлайна за, мин',
	'sleep.hotel_if_cash_after_reserve_ge': 'Отель, если 💵 после резерва не меньше',
	'levelup.policy': 'Политика прокачки',
	'battle.target': 'Цель',
	'battle.overrides': 'Цели по часу битвы (МСК)',
	'stocks.cash_floor': 'Оставлять 💵',
	'stocks.min_dump': 'Сливать от 💵',
	'stocks.sell_cap_margin': 'Запас до лимита продажи',
	'stocks.dump_lead_min': 'За сколько минут до битвы, мин',
	'tangerine.interval_h': 'Период /gt, ч',
	'metro.min_budget_min': 'Минимальный бюджет забега, мин',
	'metro.battle_margin_min': 'Запас до битвы, мин',
	'metro.extra_margin_min': 'Свой запас, мин',
	'metro.buffs': 'Бафы',
	'metro.heal_at': 'Аптечка при 🔋 не выше',
	'metro.heal_before_exit': 'Долечиться перед выходом',
	'metro.chest_min_packs': 'Открывать сундук при аптечках от',
	'metro.npc_low_enabled': 'Драться со слабым NPC',
	'metro.npc_high_enabled': 'Драться с сильным NPC',
	'metro.npc_min_stamina': 'Без аптечек не драться при 🔋 ниже',
	'daily.personal_order': 'Порядок личных заданий',
	'lottery.tickets': 'Билетов за тираж',
	'lottery.tickets.money': '💵',
	'lottery.tickets.knowledge': '📚',
	'lottery.tickets.raw': '🔩',
	'lottery.tickets.details': '⚙️',
	'lottery.keep': 'Не тратить на билеты',
	'lottery.keep.money': '💵 ниже',
	'lottery.keep.knowledge': '📚 ниже',
	'lottery.keep.raw': '🔩 ниже',
	'lottery.keep.details': '⚙️ ниже',
	'retention.messages_days': 'Сообщения и действия, дней',
	'retention.decisions_days': 'Решения, дней',
	'retention.metrics_days': 'Метрики, дней'
};
