services:
  pyrobot:
    build: .
    container_name: pyrobot
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
      SENTRY_DSN: http://7bb6c1f1-6ad9-45ae-b764-33c6bc132411@10.10.40.40:8000/12
      ENVIRONMENT: production
    volumes:
      - ./sessions/harvestsession.session:/app/harvestsession.session
